name: cv2
channels:
  - defaults
dependencies:
  - pytorch=1.4.0 
  - numpy=1.18.1
  - matplotlib=3.1.3
  - pip=20.0.2
  - python=3.8.3
  - h5py=2.10.0
  - zlib=1.2.11
  - pip:
    - dlib==19.19.0
    - pillow==7.1.2
prefix: ~/.conda/envs/cv2

